[package]
name = "catsay"
version = "0.1.0"
authors = ["Thiago Gorgulho Leão <burningbluefox@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.14"
colored = "1.9.3"
failure = "0.1.7"